# **<u>Proyecto final Datos No Estructurados y Semiestructurados 2026 - Federico Vecchio</u>**

Motiva este proyecto el conocer la percepción que tienen los clientes en redes sociales acerca del funcionamiento de los autómatas bancarios (ATMs, buzoneras, reconocedoras) del BROU. En particular, interesa saber acerca de las reseñas de Google Maps publicadas en el año 2025. Tener este insumo podría ser de utilidad no solo a la hora de ajustar aspectos de monitoreo interno de los autómatas bancarios, sino también a la hora de ajustar condiciones contractuales con los proveedores de los servicios relacionados al mantenimiento y asistencia técnica de los mismos.

---

## 1 - Bajar los datos

Obtención de los URL/PlaceID para luego obtener las reviews de Sucursales/ATMs BROU en Apify

In [ ]:
#!pip install apify

from apify_client import ApifyClient
import pandas as pd

client = ApifyClient("mi_token_de_apify")

#Obtener las URL/PlaceID para traer las reseñas en Apify:
run_input = {
    "searchStringsArray": [
        "BROU sucursal",
        "BROU cajero automático",
        "Banco República cajero"
    ],
    "locationQuery": "Uruguay",
    "maxCrawledPlacesPerSearch": 120,  # tope por búsqueda, así que conviene desglosar
    "language": "es"
}

run = client.actor("compass/crawler-google-places").call(run_input=run_input)

items = list(client.dataset(run["defaultDatasetId"]).iterate_items())
df = pd.DataFrame(items)

# Interesan estas columnas para el siguiente paso
sucursales = df[["title", "address", "placeId", "url", "totalScore", "reviewsCount"]]
sucursales = sucursales.drop_duplicates(subset="placeId")
sucursales.to_csv("sucursales_brou.csv", index=False)

[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> Status: RUNNING, Message:
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:15.829Z ACTOR: Pulling container image of build 0uefwfDJkljbv566W from registry.
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:15.831Z ACTOR: Creating container.
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:15.871Z ACTOR: Starting container.
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:15.871Z ACTOR: Running under "LIMITED_PERMISSIONS".
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:17.052Z INFO  System info {"apifyVersion":"3.7.2","apifyClientVersion":"2.23.4","crawleeVersion":"3.16.0","osType":"Linux","nodeVersion":"v24.18.0"}
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:17.496Z INFO  📡 Geolocation started
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:17.521Z INFO  Looking for geolocation for user input: "Uruguay"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:17.683Z INFO  📡 Location GEOLOCATED as (check this is correct): "Uruguay, lat: -32.8755548, long: -56.0201525"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:17.683Z INFO  [Status message]: 📡 Map polygon created.
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:17.683Z         You can visually check the exact area that will be scanned for places here:
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:17.684Z https://nominatim.openstreetmap.org/ui/search.html?q=Uruguay
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:17.852Z INFO  📡 Created 8 map polygons with total area: 201207.43km2
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> Status: RUNNING, Message: 📡 Map polygon created.
        You can visually check the exact area that will be scanned for places here:
https://nominatim.openstreetmap.org/ui/search.html?q=Uruguay
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:17.853Z INFO  📡 The location was split into 83 map segments. Each is converted into differenly located search page URL for each search term to ensure maximum coverage.
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.059Z INFO  📡 Geolocation finished
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.065Z INFO  📡 Getting geolocation for 10 cities in the area and adding them to the search queue
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.065Z INFO  Looking for geolocation for user input: "city: Montevideo, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.065Z INFO  Looking for geolocation for user input: "city: Salto, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.066Z INFO  Looking for geolocation for user input: "city: Paysandú, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.066Z INFO  Looking for geolocation for user input: "city: Las Piedras, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.066Z INFO  Looking for geolocation for user input: "city: Rivera, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.066Z INFO  Looking for geolocation for user input: "city: Maldonado, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.067Z INFO  Looking for geolocation for user input: "city: Tacuarembó, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.067Z INFO  Looking for geolocation for user input: "city: Melo, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.067Z INFO  Looking for geolocation for user input: "city: Mercedes, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.067Z INFO  Looking for geolocation for user input: "city: Artigas, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.332Z INFO  Loaded geolocation for 10/144 cities and added them to the search queue
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.333Z INFO  Added 441 map segments, total 524 map segments
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.514Z INFO  📡 Getting geolocation for 10 cities in the area and adding them to the search queue
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.515Z INFO  Looking for geolocation for user input: "city: Minas, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.515Z INFO  Looking for geolocation for user input: "city: San José de Mayo, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.515Z INFO  Looking for geolocation for user input: "city: Durazno, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.516Z INFO  Looking for geolocation for user input: "city: Florida, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.516Z INFO  Looking for geolocation for user input: "city: Barros Blancos, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.516Z INFO  Looking for geolocation for user input: "city: San Carlos, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.517Z INFO  Looking for geolocation for user input: "city: Treinta y Tres, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.517Z INFO  Looking for geolocation for user input: "city: Rocha, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.517Z INFO  Looking for geolocation for user input: "city: Pando, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.517Z INFO  Looking for geolocation for user input: "city: Fray Bentos, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.554Z INFO  HttpCrawler: Starting the crawler.
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.813Z INFO  Loaded geolocation for 20/144 cities and added them to the search queue
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> Status: RUNNING, Message: Starting the crawler.
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:19.814Z INFO  Added 375 map segments, total 899 map segments
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:24.437Z INFO  🔍 [BROU cajero automático][-32.9663|-58.0885][SCROLL: 1]: Search page scraped: 20 unique, 20 seen, 1 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/BROU%20cajero%20autom%C3%A1tico/@-32.96627804002827,-58.08845629046617,17z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:25.053Z INFO  📡 Getting geolocation for 10 cities in the area and adding them to the search queue
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:25.054Z INFO  Looking for geolocation for user input: "city: Colonia del Sacramento, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:25.054Z INFO  Looking for geolocation for user input: "city: Trinidad, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:25.054Z INFO  Looking for geolocation for user input: "city: La Paz, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:25.054Z INFO  Looking for geolocation for user input: "city: Canelones, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:25.055Z INFO  Looking for geolocation for user input: "city: Carmelo, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:25.055Z INFO  Looking for geolocation for user input: "city: Delta del Tigre, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:25.055Z INFO  Looking for geolocation for user input: "city: Dolores, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:25.055Z INFO  Looking for geolocation for user input: "city: Young, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:25.056Z INFO  Looking for geolocation for user input: "city: Santa Lucía, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:25.056Z INFO  Looking for geolocation for user input: "city: Progreso, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:25.364Z INFO  Loaded geolocation for 30/144 cities and added them to the search queue
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:25.365Z INFO  Added 300 map segments, total 1199 map segments
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:25.565Z INFO  🔍 [BROU sucursal][-32.9663|-58.0885][SCROLL: 2]: Search page scraped: 18 unique, 1 duplicate, 20 seen, 2 paginations, 1 outOfLocation. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/BROU%20sucursal/@-32.96627804002827,-58.08845629046617,17z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> Status: RUNNING, Message: Scraped in total 2 search pages. Found 18 new places in the last 1 search pages (18.00 places per search page). Average capture rate can drop over the course of the Actor run.
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:29.554Z INFO  Scraped in total 2 search pages. Found 18 new places in the last 1 search pages (18.00 places per search page). Average capture rate can drop over the course of the Actor run.
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.539Z INFO  📡 Getting geolocation for 10 cities in the area and adding them to the search queue
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.540Z INFO  Looking for geolocation for user input: "city: Paso de Carrasco, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.540Z INFO  Looking for geolocation for user input: "city: Río Branco, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.540Z INFO  Looking for geolocation for user input: "city: Paso de los Toros, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.542Z INFO  Looking for geolocation for user input: "city: Juan L. Lacaze, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.543Z INFO  Looking for geolocation for user input: "city: Bella Unión, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.543Z INFO  Looking for geolocation for user input: "city: Libertad, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.543Z INFO  Looking for geolocation for user input: "city: Rosario, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.544Z INFO  Looking for geolocation for user input: "city: Nueva Helvecia, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.544Z INFO  Looking for geolocation for user input: "city: Nueva Palmira, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.544Z INFO  Looking for geolocation for user input: "city: Chui, country: UY"
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.641Z WARN  📡 Could not find geolocation, skipping {"cityName":"Juan L. Lacaze","cityCountry":"UY"}
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.763Z INFO  Loaded geolocation for 40/144 cities and added them to the search queue
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.764Z INFO  Added 207 map segments, total 1406 map segments
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:30.863Z INFO  🔍 [Banco República cajero][-32.9663|-58.0885][SCROLL: 1]: Search page scraped: 10 unique, 10 duplicate, 20 seen, 1 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/Banco%20Rep%C3%BAblica%20cajero/@-32.96627804002827,-58.08845629046617,17z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:33.102Z INFO  🔍 [BROU sucursal][-35.3132|-55.7852][SCROLL: 4]: Search page scraped: 21 unique, 26 duplicate, 47 seen, 4 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/BROU%20sucursal/@-35.313158920153214,-55.785178099999996,10z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:37.495Z INFO  [Status message]: You can check all currently scraped places laid out on a map on: https://api.apify.com/v2/key-value-stores/lmyJqjvTMXxEJGYu3/records/results-map?signature=9Ix6jf0D8n1dsvbA8CrF
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:37.849Z INFO  🔍 [BROU sucursal][-33.0223|-58.1272][SCROLL: 2]: Search page scraped: 20 duplicate, 20 seen, 2 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/BROU%20sucursal/@-33.022337271334074,-58.127178450099294,17z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> Status: RUNNING, Message: You can check all currently scraped places laid out on a map on: https://api.apify.com/v2/key-value-stores/lmyJqjvTMXxEJGYu3/records/results-map?signature=9Ix6jf0D8n1dsvbA8CrF
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:38.064Z INFO  🔍 [BROU cajero automático][-35.3132|-55.7852][SCROLL: 5]: Search page scraped: 31 unique, 42 duplicate, 73 seen, 5 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/BROU%20cajero%20autom%C3%A1tico/@-35.313158920153214,-55.785178099999996,10z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> Status: RUNNING, Message: Scraped in total 6 search pages. Found 70 new places in the last 4 search pages (17.50 places per search page). Average capture rate can drop over the course of the Actor run.
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:39.554Z INFO  Scraped in total 6 search pages. Found 70 new places in the last 4 search pages (17.50 places per search page). Average capture rate can drop over the course of the Actor run.
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:40.894Z INFO  🔍 [Banco República cajero][-35.3132|-55.7852][SCROLL: 2]: Search page scraped: 40 duplicate, 40 seen, 2 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/Banco%20Rep%C3%BAblica%20cajero/@-35.313158920153214,-55.785178099999996,10z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:41.844Z INFO  🔍 [Banco República cajero][-33.0223|-58.1272][SCROLL: 1]: Search page scraped: 4 unique, 16 duplicate, 20 seen, 1 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/Banco%20Rep%C3%BAblica%20cajero/@-33.022337271334074,-58.127178450099294,17z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:42.446Z INFO  🔍 [BROU cajero automático][-33.0223|-58.1272][SCROLL: 1]: Search page scraped: 20 duplicate, 20 seen, 1 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/BROU%20cajero%20autom%C3%A1tico/@-33.022337271334074,-58.127178450099294,17z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:43.487Z INFO  🔍 [BROU sucursal][-33.0077|-58.1256][SCROLL: 1]: Search page scraped: 1 unique, 19 duplicate, 20 seen, 1 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/BROU%20sucursal/@-33.007718700000005,-58.125585599999994,18z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:45.833Z INFO  🔍 [Banco República cajero][-33.0077|-58.1256][SCROLL: 1]: Search page scraped: 20 duplicate, 20 seen, 1 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/Banco%20Rep%C3%BAblica%20cajero/@-33.007718700000005,-58.125585599999994,18z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:47.682Z INFO  🔍 [BROU cajero automático][-33.0077|-58.1256][SCROLL: 1]: Search page scraped: 20 duplicate, 20 seen, 1 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/BROU%20cajero%20autom%C3%A1tico/@-33.007718700000005,-58.125585599999994,18z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:49.554Z INFO  Scraped in total 12 search pages. Found 70 new places in the last 5 search pages (14.00 places per search page). Average capture rate can drop over the course of the Actor run.
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> Status: RUNNING, Message: Scraped in total 12 search pages. Found 70 new places in the last 5 search pages (14.00 places per search page). Average capture rate can drop over the course of the Actor run.
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:49.741Z INFO  🔍 [Banco República cajero][-33.0007|-58.1186][SCROLL: 2]: Search page scraped: 1 unique, 19 duplicate, 20 seen, 2 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/Banco%20Rep%C3%BAblica%20cajero/@-33.000715639332974,-58.118582350000004,17z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:50.324Z INFO  🔍 [BROU sucursal][-33.0007|-58.1186][SCROLL: 2]: Search page scraped: 20 duplicate, 20 seen, 2 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/BROU%20sucursal/@-33.000715639332974,-58.118582350000004,17z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:51.804Z INFO  🔍 [BROU cajero automático][-33.0007|-58.1186][SCROLL: 1]: Search page scraped: 20 duplicate, 20 seen, 1 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/BROU%20cajero%20autom%C3%A1tico/@-33.000715639332974,-58.118582350000004,17z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:52.495Z INFO  🔍 [BROU sucursal][-31.5064|-54.6119][SCROLL: 3]: Search page scraped: 8 unique, 14 duplicate, 22 seen, 3 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/BROU%20sucursal/@-31.506407927908082,-54.61190504289085,10z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:53.573Z INFO  🔍 [BROU cajero automático][-31.5064|-54.6119][SCROLL: 1]: Search page scraped: 4 unique, 16 duplicate, 20 seen, 1 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/BROU%20cajero%20autom%C3%A1tico/@-31.506407927908082,-54.61190504289085,10z?hl=es
[apify.crawler-google-places runId:Kw7OmZbM6lUkJzphi] -> 2026-06-28T00:29:55.593Z INFO  🔍 [BROU cajero automático][-33.0113|-58.1256][SCROLL: 1]: Search page scraped: 3 unique, 17 duplicate, 20 seen, 1 paginations. No more places found on this page. (no next cursor) --- https://www.google.com/maps/search/BROU%20cajero%20autom%C3%A1tico/@-33.01132174573895,-58.125585599999994,18z?hl=es

Completó el proceso pero se cayó antes de llegar a descargar los resultados a un DataFrame

In [ ]:

# Recuperar los datos sin volver a correr el scraping:

run_id = "UnwUafxSLPketpoR6"  # el que tiró el log; el dataset generado que quedó guardado en apify

run = client.run(run_id).get()
dataset_id = run["defaultDatasetId"]

items = list(client.dataset(dataset_id).iterate_items())
df = pd.DataFrame(items)

print(len(df), "lugares encontrados")
df.head()

299 lugares encontrados

,title,subTitle,description,price,categoryName,address,neighborhood,street,city,postalCode,...,url,searchPageUrl,searchString,language,rank,isAdvertisement,imageUrl,kgmid,additionalInfo,reviewsDistribution
0,RedBROU,None,None,None,Cajeros automáticos,"3QVX+3RG, Liniers, 11000 Montevideo, Departame...",NaN,"3QVX+3RG, Liniers",Montevideo,11000,...,https://www.google.com/maps/search/?api=1&quer...,https://www.google.com/maps/search/Banco%20Rep...,Banco República cajero,es,1,False,https://lh3.googleusercontent.com/gps-cs-s/APN...,/g/11cjnjk4g7,NaN,NaN
1,RedBrou,None,None,None,Cajeros automáticos,"Av. Gonzalo Ramírez 2076, 11200 Montevideo, De...",NaN,Av. Gonzalo Ramírez 2076,Montevideo,11200,...,https://www.google.com/maps/search/?api=1&quer...,https://www.google.com/maps/search/Banco%20Rep...,Banco República cajero,es,2,False,https://streetviewpixels-pa.googleapis.com/v1/...,/g/1tcz9hhw,{'Accesibilidad': [{'Entrada accesible para pe...,NaN
2,Cajeros Red Brou,None,None,None,Centro comercial,"4RJJ+6CW, A., Bulevar General Artigas & Av. Dr...",NaN,"4RJJ+6CW, A., Bulevar General Artigas & Av. Dr...",Montevideo,11600,...,https://www.google.com/maps/search/?api=1&quer...,https://www.google.com/maps/search/Banco%20Rep...,Banco República cajero,es,3,False,https://lh3.googleusercontent.com/gps-cs-s/APN...,/g/11g7zt_yy5,{'Accesibilidad': [{'Entrada accesible para pe...,NaN
3,Cajero REDBROU,None,None,None,Cajeros automáticos,"Av. 25 de Mayo 3375, 65000 Fray Bentos, Depart...",NaN,Av. 25 de Mayo 3375,Fray Bentos,65000,...,https://www.google.com/maps/search/?api=1&quer...,https://www.google.com/maps/search/Banco%20Rep...,Banco República cajero,es,4,False,https://streetviewpixels-pa.googleapis.com/v1/...,/g/11g9k46kvs,{'Accesibilidad': [{'Entrada accesible para pe...,NaN
4,Banco República,None,None,None,Banco,"Av. 25 de Mayo 3375, 65000 Fray Bentos, Depart...",NaN,Av. 25 de Mayo 3375,Fray Bentos,NaN,...,https://www.google.com/maps/search/?api=1&quer...,https://www.google.com/maps/search/Banco%20Rep...,Banco República cajero,es,5,False,https://lh3.googleusercontent.com/gps-cs-s/APN...,/g/11bv1997mm,{'Accesibilidad': [{'Entrada accesible para pe...,NaN

In [ ]:
#1. Bajar el dataset a un DataFrame

from apify_client import ApifyClient
import pandas as pd

client = ApifyClient("mi_token_de_apify")

dataset_id = "vMZAoTM9785KsUtsV" #este id es diferente al anterior pero el dataset es el mismo
items = list(client.dataset(dataset_id).iterate_items())
df = pd.DataFrame(items)

print(len(df))
df[["title", "categoryName", "address", "reviewsCount"]].head(20)

299

,title,categoryName,address,reviewsCount
0,RedBROU,Cajeros automáticos,"3QVX+3RG, Liniers, 11000 Montevideo, Departame...",9.0
1,RedBrou,Cajeros automáticos,"Av. Gonzalo Ramírez 2076, 11200 Montevideo, De...",8.0
2,Cajeros Red Brou,Centro comercial,"4RJJ+6CW, A., Bulevar General Artigas & Av. Dr...",3149.0
3,Cajero REDBROU,Cajeros automáticos,"Av. 25 de Mayo 3375, 65000 Fray Bentos, Depart...",1.0
4,Banco República,Banco,"Av. 25 de Mayo 3375, 65000 Fray Bentos, Depart...",43.0
5,Banco República,Banco,"Ruta 2 Km 209.500 José Enrique Rodó, José Enri...",10.0
6,Banco República,Banco,"Jose Ugarte 1690, 65100 Young, Departamento de...",13.0
7,Banco Republica,Banco,"Jose Pedro Varela 1185, 70400 Colonia Valdense...",12.0
8,Banco República,Banco,Horario de atención al público de 13 a 18 hora...,29.0
9,RedBROU,Cajeros automáticos,"Av. 8 de Octubre 3181, 11600 Montevideo, Depar...",27.0
10,Banco República,Banco,"Piedras 370, 11000 Montevideo, Departamento de...",184.0
11,RedBROU Sucursal Maldonado,Cajeros automáticos,"Florida 669, 20000 Maldonado, Departamento de ...",8.0
12,RedBROU,Cajeros automáticos,"4R56+FHH, 11800 Montevideo, Departamento de Mo...",6.0
13,BROU - Nuevo Berlín,Banco,"65000 Nuevo Berlín, Departamento de Río Negro,...",4.0
14,Cajeros BROU,Cajeros automáticos,"Av. Sarandí 950, 40000 Rivera, Departamento de...",12.0
15,RedBROU,Cajeros automáticos,"4R99+R8J, Av. Gral. Flores, 11800 Montevideo, ...",20.0
16,Cajero BROU,Cajeros automáticos,"Continuacion Montevideo 961, 60000 Paysandú, D...",8.0
17,Cajero Red BROU,Cajeros automáticos,"79X8+VFX, Gral. Artigas, 65100 Young, Departam...",1.0
18,RedBROU,Cajeros automáticos,"Acevedo Díaz 1650, 11200 Montevideo, Departame...",11.0
19,Banco República,Banco,"18 de Julio 136 esquina, Dr. Raul Martini, Que...",5.0

In [7]:
#2.1 Filtrar falsos positivos

# Qué categorías/títulos aparecieron
df["categoryName"].value_counts()
df["title"].sample(20)

19                                Banco República
94                                        RedBROU
244                                        Banred
90     Banco de la República - Anexo Casa Central
186                                Cajero REDBROU
122                               Banco República
256                             Cajero Automático
32                                       RED BROU
202                               Banco República
236                                       REDBROU
295                                Cajero Redbrou
31                                        REDBROU
52                                    Cajero Brou
0                                         RedBROU
2                                Cajeros Red Brou
87                                 Cajero RedBROU
154                                       REDBROU
125                               Banco República
134                               Banco República
275                                       RedBROU
Name: title, dtype: str

In [ ]:
# 2.2 Filtrar por lo que efectivamente sea BROU

df_filtrado = df[df["title"].str.contains("BROU|Banco República", case=False, na=False)]
print(len(df_filtrado))

277

In [9]:
#3. Quitar duplicados y lugares sin reviews

df_filtrado = df_filtrado.drop_duplicates(subset="placeId")
df_con_reviews = df_filtrado[df_filtrado["reviewsCount"] > 0]
print(len(df_con_reviews), "lugares con al menos 1 review")

254 lugares con al menos 1 review

In [ ]:
#Estimar el costo total
#total_reviews = df_con_reviews["reviewsCount"].sum()
#print(f"Total estimado de reviews: {total_reviews}")
#print(f"Costo estimado: ${(total_reviews / 1000) * 0.25:.2f}")

#Costo del scraping de reviews; para reducir este costo es que primero se filtraron los lugares que efectivamente sean del BROU y que tengan al menos 1 review

Total estimado de reviews: 8365.0
Costo estimado: $2.09

Dataset filtrado --> 254 lugares con reseñas de las 299 que trajo en primera instancia

In [ ]:
#Guardar el dataset filtrado:
from apify_client import ApifyClient

client = ApifyClient("mi_token_de_apify")

df_con_reviews.to_csv("sucursales_filtradas_254.csv", index=False)

- Correr el código para obtener las reseñas de los 254 lugares que pertenecen a la red de ATMs del Banco República

In [ ]:
#Versión "Robusta" a cortes/interrupciones

import pandas as pd
import time
import json
from apify_client import ApifyClient

client = ApifyClient("mi_token_de_apify")

df_con_reviews = pd.read_csv("sucursales_filtradas_254.csv")

run_input = {
    "startUrls": [{"url": url} for url in df_con_reviews["url"]],
    "reviewsOrigin": "google",
    "maxReviews": 9999, #techo que abarca todas las reseñas (8365 en total); esta versión del actor no acepta "0" para que la cantidad de reseñas no tenga un tope
    "language": "es"
}

# Versión "robusta" a cortes/interrupciones
run = client.actor("compass/google-maps-reviews-scraper").start(run_input=run_input)
run_id = run["id"]
print("Run ID:", run_id)

with open("run_id_reviews.txt", "w") as f:
    f.write(run_id)

while True:
    try:
        status = client.run(run_id).get()["status"]
        print("Estado:", status)
        if status in ("SUCCEEDED", "FAILED", "ABORTED", "TIMED-OUT"):
            break
    except Exception as e:
        print(f"Error de conexión al chequear estado, reintentando: {e}")
    time.sleep(30)

dataset_id_reviews = client.run(run_id).get()["defaultDatasetId"]
print("Dataset listo:", dataset_id_reviews)

# Bajar los items y guardar el JSON crudo ANTES de aplanar a tabla
items = list(client.dataset(dataset_id_reviews).iterate_items())

with open("reviews_brou_raw.json", "w", encoding="utf-8") as f:
    json.dump(items, f, ensure_ascii=False, indent=2)

print(f"{len(items)} reviews guardadas en JSON crudo")

Run ID: TZwCU1RKLNLilDDEK
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: RUNNING
Estado: SUCCEEDED
Dataset listo: ys13tt91O6hXY56ac
8333 reviews guardadas en JSON crudo

Quedó listo el archivo JSON con las reseñas para comenzar a trabajarlo

---

## 2 - Limpiar

In [73]:
import json
import pandas as pd

# Exploración inicial del archivo JSON

with open("reviews_brou_raw.json", "r", encoding="utf-8") as f:
    items = json.load(f)

print(f"Total de reviews: {len(items)}")
print(f"\n--- Claves disponibles en cada registro ---")
print(list(items[0].keys()))
print(f"\n--- Primer registro completo ---")
print(json.dumps(items[0], indent=2, ensure_ascii=False))

Total de reviews: 8333

--- Claves disponibles en cada registro ---
['searchString', 'reviewerId', 'reviewerUrl', 'name', 'reviewerNumberOfReviews', 'isLocalGuide', 'reviewerPhotoUrl', 'text', 'textTranslated', 'publishAt', 'publishedAtDate', 'likesCount', 'reviewId', 'reviewUrl', 'reviewOrigin', 'stars', 'rating', 'responseFromOwnerDate', 'responseFromOwnerText', 'reviewImageUrls', 'reviewContext', 'reviewDetailedRating', 'visitedIn', 'originalLanguage', 'translatedLanguage', 'isAdvertisement', 'placeId', 'location', 'address', 'neighborhood', 'street', 'city', 'postalCode', 'state', 'countryCode', 'categoryName', 'categories', 'title', 'totalScore', 'permanentlyClosed', 'temporarilyClosed', 'reviewsCount', 'url', 'price', 'cid', 'fid', 'hotelStars', 'imageUrl', 'scrapedAt', 'language', 'kgmid']

--- Primer registro completo ---
{
  "searchString": "Direct Detail URL: https://www.google.com/maps/search/?api=1&query=Banco%20Rep%C3%BAblica&query_place_id=ChIJh4kKqQ2do5URfOys70_SHFY",
  "reviewerId": "114487066169244077460",
  "reviewerUrl": "https://www.google.com/maps/contrib/114487066169244077460?hl=es",
  "name": "Victor Ricca",
  "reviewerNumberOfReviews": 6,
  "isLocalGuide": false,
  "reviewerPhotoUrl": "https://lh3.googleusercontent.com/a-/ALV-UjV5zklQvnMGkn4mNHc2bmbNr7Mm3zJwzzo4QD57i0vKGfqwp1yE=s1920-c-rp-mo-br100",
  "text": null,
  "textTranslated": null,
  "publishAt": "Hace un año",
  "publishedAtDate": "2025-06-05T10:43:21.452Z",
  "likesCount": 0,
  "reviewId": "ChZDSUhNMG9nS0VJeTctNXJSaWQycU9nEAE",
  "reviewUrl": "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJeTctNXJSaWQycU9nEAE!2m1!1s0x0:0x561cd24fefacec7c!3m1!1s2@1:CIHM0ogKEIy7-5rRid2qOg%7C%7C?hl=es",
  "reviewOrigin": "Google",
  "stars": 5,
  "rating": null,
  "responseFromOwnerDate": null,
  "responseFromOwnerText": null,
  "reviewImageUrls": [],
  "reviewContext": {},
  "reviewDetailedRating": {},
  "visitedIn": null,
  "originalLanguage": null,
  "translatedLanguage": null,
  "isAdvertisement": false,
  "placeId": "ChIJh4kKqQ2do5URfOys70_SHFY",
  "location": {
    "lat": -34.2650529,
    "lng": -57.6115366
  },
  "address": "Bartolomé Bacigalupe 2292, 70600 Tarariras, Departamento de Colonia, Uruguay",
  "neighborhood": null,
  "street": "Bartolomé Bacigalupe 2292",
  "city": "Tarariras",
  "postalCode": null,
  "state": "Departamento de Colonia",
  "countryCode": "UY",
  "categoryName": "Banco",
  "categories": [
    "Banco"
  ],
  "title": "Banco República",
  "totalScore": 4,
  "permanentlyClosed": false,
  "temporarilyClosed": false,
  "reviewsCount": 13,
  "url": "https://www.google.com/maps/search/?api=1&query=Banco%20Rep%C3%BAblica&query_place_id=ChIJh4kKqQ2do5URfOys70_SHFY",
  "price": null,
  "cid": "6205065627375037564",
  "fid": "0x95a39d0da90a8987:0x561cd24fefacec7c",
  "hotelStars": null,
  "imageUrl": "https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=ERdICA4g8gBhedPC84dEbQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=4.317687&pitch=1.7213143&thumbfov=100",
  "scrapedAt": "2026-06-28T00:49:44.583Z",
  "language": "es",
  "kgmid": "/g/1tffkzc7"
}

Columnas candidatas a la tabla final:
- reviewId --> primary key
- name --> Google reviews no permite reviews anónimas reales; para filtrar aquellos anónimos por usar "apodos" o nombres "fantasía"?
- title --> nombre del lugar
- address --> ubicación
- city --> ubicación
- categoryName - tipo de lugar (Banco, Cajero automático, etc)
- stars
- text --> fundamental, es el texto de la reseña
- textTranslated
- originalLanguage --> idioma original de la review
- publishedAtDate --> fecha en formato ISO
- reviewerNumberOfReviews --> reviewer casual?
- responseFromOwnerText --> respuesta del BROU

In [75]:
# Aplanar a DataFrame con las columnas candidatas
columnas = [
    "reviewId",
    "name",
    "title",
    "address",
    "city",
    "categoryName",
    "stars",
    "text",
    "textTranslated",
    "originalLanguage",
    "publishedAtDate",
    "reviewerNumberOfReviews",
    "responseFromOwnerText"
]

df = pd.DataFrame(items)[columnas].copy()

# Convertir fecha a datetime
df["publishedAtDate"] = pd.to_datetime(df["publishedAtDate"])

print(f"Shape: {df.shape}")
print(f"\n--- Primeras filas ---")
print(df.head())

Shape: (8333, 13)

--- Primeras filas ---
                               reviewId                 name            title  \
0   ChZDSUhNMG9nS0VJeTctNXJSaWQycU9nEAE         Victor Ricca  Banco República
1   ChZDSUhNMG9nS0VKTy0yNE8yamVId2J3EAE  Jorge Ariel Morales  Banco República
2   ChZDSUhNMG9nS0VJQ0FnSUQtblB2UlVBEAE     gustavo elizarzu  Banco República
3  ChdDSUhNMG9nS0VJQ0FnSURLOHJpSDRnRRAB   Rolando Lazzarotti  Banco República
4   ChZDSUhNMG9nS0VJQ0FnSURLa3ZEdldBEAE      Milton Gonzalez  Banco República

                                             address       city categoryName  \
0  Bartolomé Bacigalupe 2292, 70600 Tarariras, De...  Tarariras        Banco
1  Bartolomé Bacigalupe 2292, 70600 Tarariras, De...  Tarariras        Banco
2  Bartolomé Bacigalupe 2292, 70600 Tarariras, De...  Tarariras        Banco
3  Bartolomé Bacigalupe 2292, 70600 Tarariras, De...  Tarariras        Banco
4  Bartolomé Bacigalupe 2292, 70600 Tarariras, De...  Tarariras        Banco

   stars                                               text textTranslated  \
0      5                                                NaN            NaN
1      5                                                NaN            NaN
2      5                                Muy buena atención.            NaN
3      5  Excelente, atención cordial y amena, solución ...            NaN
4      4                                Muy bueno impecable            NaN

  originalLanguage                  publishedAtDate  reviewerNumberOfReviews  \
0              NaN 2025-06-05 10:43:21.452000+00:00                        6
1              NaN 2025-05-06 16:46:54.552000+00:00                      108
2               es 2022-11-23 20:06:55.667000+00:00                        7
3               es 2021-05-06 15:41:30.379000+00:00                      292
4               es 2021-05-05 18:32:58.732000+00:00                      123

  responseFromOwnerText
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN

In [76]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8333 entries, 0 to 8332
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   reviewId                 8333 non-null   str
 1   name                     8333 non-null   str
 2   title                    8333 non-null   str
 3   address                  8333 non-null   str
 4   city                     8333 non-null   str
 5   categoryName             8327 non-null   str
 6   stars                    8333 non-null   int64
 7   text                     4600 non-null   str
 8   textTranslated           109 non-null    str
 9   originalLanguage         4600 non-null   str
 10  publishedAtDate          8333 non-null   datetime64[us, UTC]
 11  reviewerNumberOfReviews  8333 non-null   int64
 12  responseFromOwnerText    2 non-null      str
dtypes: datetime64[us, UTC](1), int64(2), str(10)
memory usage: 846.4 KB

- Dato más relevante: 4600 reseñas con texto --> son las que nos interesan

Análisis de algunas de las variables de interés:

In [77]:
# categoryName
print(df['categoryName'].value_counts())

categoryName
Banco                     4432
Centro comercial          3116
Cajeros automáticos        715
Oficinas de empresa         24
Supermercado                16
Bancos y finanzas           15
Institución financiera       6
Club nocturno                3
Name: count, dtype: int64

- "Club nocturno" corresponde a la Chacra Banco República, donde no hay cajeros automáticos. Filas propensas a ser eliminadas junto con los 6 NA cuando se filtre por las reseñas que hablan de ATMs
- "Cajeros automáticos" --> posiblemente sea la única categoría donde las reseñas tengan relación al funcionamiento de los autómatas bancarios. No obstante, no excluye a las demás categorías

In [78]:
# originalLanguage
df['originalLanguage'].value_counts()

originalLanguage
es         4464
en           68
pt           23
es-419       14
de            6
fr            5
nl            3
ru            2
zh            2
la            2
gn            1
ja            1
iw            1
el            1
zh-Hant       1
et            1
gl            1
haw           1
ha            1
ro            1
ht            1
Name: count, dtype: int64

- 122 reviews donde el idioma es diferente al español, de las cuales hay 109 traducidas. Las restantes probablemente se deba a que no tienen traducción automática

In [79]:
# responseFromOwnerText

df['responseFromOwnerText'].value_counts()

responseFromOwnerText
¡Muchas gracias por tu comentario!                                                                                                                                    1
Carmen, nuestra agencia ubicada dentro de la sucursal del BROU en Nuevocentro Shopping se encuentra abierta de lunes a viernes en el horario de 13 a 18 h. Saludos    1
Name: count, dtype: int64

- Columna que no es relevante para el análisis pero es un dato a tener en cuenta. 
- En todo caso interesa saber si hubo respuesta del Owner (el Banco), no qué respondió --> crear nueva variable bool con *TRUE* para aquellas reseñas que tuvieron respuesta y *FALSE* en caso contrario

In [80]:
# publishedAtDate

df['publishedAtDate'].head()

0   2025-06-05 10:43:21.452000+00:00
1   2025-05-06 16:46:54.552000+00:00
2   2022-11-23 20:06:55.667000+00:00
3   2021-05-06 15:41:30.379000+00:00
4   2021-05-05 18:32:58.732000+00:00
Name: publishedAtDate, dtype: datetime64[us, UTC]

- Obs.: Transformar para que quede solo YYYY-mm-dd

---

## 3 - Procesar

In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8333 entries, 0 to 8332
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   reviewId                 8333 non-null   str
 1   name                     8333 non-null   str
 2   title                    8333 non-null   str
 3   address                  8333 non-null   str
 4   city                     8333 non-null   str
 5   categoryName             8327 non-null   str
 6   stars                    8333 non-null   int64
 7   text                     4600 non-null   str
 8   textTranslated           109 non-null    str
 9   originalLanguage         4600 non-null   str
 10  publishedAtDate          8333 non-null   datetime64[us, UTC]
 11  reviewerNumberOfReviews  8333 non-null   int64
 12  responseFromOwnerText    2 non-null      str
dtypes: datetime64[us, UTC](1), int64(2), str(10)
memory usage: 846.4 KB

In [82]:
# Búsqueda de reviews duplicadas por reviewId (duplicados exactos de registro)
dup_id = df.duplicated(subset="reviewId", keep=False)
print(f"Reviews con reviewId duplicado: {dup_id.sum()}")

Reviews con reviewId duplicado: 0

In [83]:
# Sobreescribir 'text' con 'textTranslated' donde corresponda
mask = df["textTranslated"].notna()
df.loc[mask, "text"] = df.loc[mask, "textTranslated"]

print(f"Reviews actualizadas con textTranslated: {mask.sum()}")
print(f"Reviews con texto luego del reemplazo: {df['text'].notna().sum()}")

Reviews actualizadas con textTranslated: 109
Reviews con texto luego del reemplazo: 4600

In [84]:
# Luego de sobreescribir con 'textTranslated', ya no interesa dejarla en el dataset --> se elimina

df = df.drop(columns=["textTranslated"])

In [85]:
# Elliminar reviews sin texto --> no interesan
df = df[df["text"].notna()].reset_index(drop=True)
print(f"Shape luego de eliminar sin texto: {df.shape}")

Shape luego de eliminar sin texto: (4600, 12)

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   reviewId                 4600 non-null   str
 1   name                     4600 non-null   str
 2   title                    4600 non-null   str
 3   address                  4600 non-null   str
 4   city                     4600 non-null   str
 5   categoryName             4598 non-null   str
 6   stars                    4600 non-null   int64
 7   text                     4600 non-null   str
 8   originalLanguage         4600 non-null   str
 9   publishedAtDate          4600 non-null   datetime64[us, UTC]
 10  reviewerNumberOfReviews  4600 non-null   int64
 11  responseFromOwnerText    2 non-null      str
dtypes: datetime64[us, UTC](1), int64(2), str(9)
memory usage: 431.4 KB

In [87]:
# Imputar los valores nulos de 'categoryName' con el texto 'Sin dato' para evitar posibles problemas en el análisis posterior

df["categoryName"] = df["categoryName"].fillna("Sin dato")
print(f"Nulos en categoryName: {df['categoryName'].isnull().sum()}")

Nulos en categoryName: 0

In [88]:
# Nueva variable booleana que indique si hubo respuesta del Owner
df["responseFromOwner"] = df["responseFromOwnerText"].notna()
print(df["responseFromOwner"].value_counts())

responseFromOwner
False    4598
True        2
Name: count, dtype: int64

- Obs.: Esta información no interesa a los efectos de responder la pregunta que motiva este trabajo, pero puede ser interesante tenerla para análisis futuros

In [89]:
# Se elimina la columna 'responseFromOwnerText', la información relevante ya queda capturada en la nueva variable
df = df.drop(columns=["responseFromOwnerText"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   reviewId                 4600 non-null   str
 1   name                     4600 non-null   str
 2   title                    4600 non-null   str
 3   address                  4600 non-null   str
 4   city                     4600 non-null   str
 5   categoryName             4600 non-null   str
 6   stars                    4600 non-null   int64
 7   text                     4600 non-null   str
 8   originalLanguage         4600 non-null   str
 9   publishedAtDate          4600 non-null   datetime64[us, UTC]
 10  reviewerNumberOfReviews  4600 non-null   int64
 11  responseFromOwner        4600 non-null   bool
dtypes: bool(1), datetime64[us, UTC](1), int64(2), str(8)
memory usage: 399.9 KB

In [90]:
# Nos interesan las reviews publicadas en el año 2025
# Primero ver cuántas reviews hay por año
df["publishedAtDate"].dt.year.value_counts().sort_index()

publishedAtDate
2012      2
2013      1
2014      7
2015     13
2016    130
2017    415
2018    300
2019    316
2020    551
2021    539
2022    365
2023    435
2024    570
2025    467
2026    489
Name: count, dtype: int64

In [91]:
# Filtramos por aquellas reviews publicadas en 2025
df = df[df["publishedAtDate"].dt.year == 2025].reset_index(drop=True)
print(f"Shape luego del filtro temporal: {df.shape}")

Shape luego del filtro temporal: (467, 12)

In [92]:
# Normalizar 'text' para luego filtrar por keywords y quedarnos con las reviews que efectivamente sean de interés

import unicodedata
import re

def normalizar(texto):
    # 1. lowercase
    texto = texto.lower()
    # 2. sacar acentos
    texto = unicodedata.normalize('NFKD', texto)
    texto = ''.join(c for c in texto if not unicodedata.combining(c))
    # 3. eliminar caracteres especiales
    texto = re.sub(r'[^a-z0-9\s]', ' ', texto)
    # 4. colapsar espacios múltiples
    texto = re.sub(r'\s+', ' ', texto).strip()
    return texto

df["text_normalizado"] = df["text"].apply(normalizar)

# Verificación
print(df[["text", "text_normalizado"]].head(3))

                                                text  \
0  Desde que explotó no lo han arreglado\n**YA LO...
1  Muy lalo figura com 24 hora y cuando vas esta ...
2  Como todo cajero brou me cobro 1.50 dólares pe...

                                    text_normalizado
0  desde que exploto no lo han arreglado ya lo ar...
1  muy lalo figura com 24 hora y cuando vas esta ...
2  como todo cajero brou me cobro 1 50 dolares pe...

In [93]:
# Filtrar por keywords:

keywords = ["cajero", "automata", "buzonera", "reconocedora",
            "redbrou", "atm", "billete", "efectivo", "tarjeta", "maquina",
            "cajeros", "maquinas", "billetes"]

patron = "|".join(keywords)

mask = df["text_normalizado"].str.contains(patron, case=False, na=False)
print(f"Reviews que mencionan autómatas: {mask.sum()} de {len(df)}")

df_automatas = df[mask].reset_index(drop=True)

Reviews que mencionan autómatas: 91 de 467

In [94]:
df_automatas.info()

<class 'pandas.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   reviewId                 91 non-null     str
 1   name                     91 non-null     str
 2   title                    91 non-null     str
 3   address                  91 non-null     str
 4   city                     91 non-null     str
 5   categoryName             91 non-null     str
 6   stars                    91 non-null     int64
 7   text                     91 non-null     str
 8   originalLanguage         91 non-null     str
 9   publishedAtDate          91 non-null     datetime64[us, UTC]
 10  reviewerNumberOfReviews  91 non-null     int64
 11  responseFromOwner        91 non-null     bool
 12  text_normalizado         91 non-null     str
dtypes: bool(1), datetime64[us, UTC](1), int64(2), str(9)
memory usage: 8.7 KB

In [95]:
# Creamos una nueva columna, "motivo_review", para indicar el tema que motivó la redacción de la review

motivos = {
    "dispensado": ["dispenso", "dispensar", "billete", "efectivo", "plata", "dinero"],
    "comprobante": ["comprobante", "ticket", "recibo", "imprimio", "imprime", "impresion"],
    "lentitud": ["lento", "lenta", "lentitud", "demora", "demoro", "tarda", "tardo", "espera", "cola", "fila"],
    "limpieza": ["sucio", "sucia", "limpieza", "mugre", "mugriento", "deteriorado"],
    "disponibilidad servicio": ["apagado", "apagada", "cerrado", "fuera de servicio", "no disponible", 
                                "sin servicio", "no funciona", "no anda", "inhabilitado", "falla", 
                                "fallo", "error", "trabo", "trabado", "trago", "atasca", "atascada", 
                                "no lee", "no reconoce", "bloqueado"]
}

def clasificar_motivo(texto):
    matches = []
    for motivo, keywords in motivos.items():
        patron = "|".join(keywords)
        if re.search(patron, texto):
            matches.append(motivo)
    return matches if matches else ["otro"]

df_automatas["motivo_review"] = df_automatas["text_normalizado"].apply(clasificar_motivo)

# Verificación
print(df_automatas[["text", "motivo_review"]].head(10))
print("\n--- Distribución de motivos ---")
from collections import Counter
todos_motivos = [m for lista in df_automatas["motivo_review"] for m in lista]
print(Counter(todos_motivos))

                                                text  \
0  Como todo cajero brou me cobro 1.50 dólares pe...
1  Dos cajeros y dos máquinas de depósito. Funcio...
2  Un solo cajero para retirar dinero, alguna vez...
3  Si tenés que renovar tu tarjeta anda pensando ...
4  Depositas plata, la máquina da error, no te de...
5  Muy buena atención,un lástima los indigentes q...
6  Excelente servicio, buena atención, me gusta p...
7  Buena sucursal. Atención rápida. Estacionamien...
8  Solo había un lugar en Uruguay donde podíamos ...
9  Es un lugar seguro pero algunos cajeros están ...

                                     motivo_review
0                                           [otro]
1                                           [otro]
2  [dispensado, lentitud, disponibilidad servicio]
3                                       [lentitud]
4  [dispensado, lentitud, disponibilidad servicio]
5                                           [otro]
6                                           [otro]
7                                           [otro]
8            [dispensado, disponibilidad servicio]
9                                           [otro]

--- Distribución de motivos ---
Counter({'otro': 45, 'dispensado': 23, 'lentitud': 21, 'disponibilidad servicio': 15, 'limpieza': 2, 'comprobante': 1})

In [96]:
# Para finalizar con el procesamiento del dataset, se crea una columna para indicar el "tono" de la review según la cantidad de estrellas otorgadas por el usuario
def clasificar_tono(stars):
    if stars <= 2:
        return "Negativo"
    elif stars == 3:
        return "Neutro"
    else:
        return "Positivo"

df_automatas["tono"] = df_automatas["stars"].apply(clasificar_tono)

print(df_automatas["tono"].value_counts())

tono
Positivo    43
Negativo    39
Neutro       9
Name: count, dtype: int64

In [99]:
df_automatas

,reviewId,name,title,address,city,categoryName,stars,text,originalLanguage,publishedAtDate,reviewerNumberOfReviews,responseFromOwner,text_normalizado,motivo_review,tono
0,Ci9DQUlRQUNvZENodHljRjlvT25vMk5YcDVPVFIyTVVKUU...,Adrian Arispe,Cajero BROU,"Av. Jose Gervasio Artigas 632, 15900 Las Piedr...",Las Piedras,Cajeros automáticos,3,Como todo cajero brou me cobro 1.50 dólares pe...,es,2025-09-25 08:20:04.667000+00:00,22,False,como todo cajero brou me cobro 1 50 dolares pe...,[otro],Neutro
1,Ci9DQUlRQUNvZENodHljRjlvT2tkM2FFeEVkVE01ZEhRM2...,asterion70,RedBrou,"José Ellauri 698, 11300 Montevideo, Departamen...",Montevideo,Cajeros automáticos,5,Dos cajeros y dos máquinas de depósito. Funcio...,es,2025-12-05 11:25:20.280000+00:00,45,False,dos cajeros y dos maquinas de deposito funcion...,[otro],Positivo
2,ChZDSUhNMG9nS0VJQ0FnTUNBdjlLd0ZnEAE,Cristhian Laborde,Banco República,"18 de Julio 353, 60100 Guichón, Departamento d...",Guichón,Banco,1,"Un solo cajero para retirar dinero, alguna vez...",es,2025-02-05 22:02:35.068000+00:00,35,False,un solo cajero para retirar dinero alguna vez ...,"[dispensado, lentitud, disponibilidad servicio]",Negativo
3,ChdDSUhNMG9nS0VJQ0FnSURfaHVEYXlRRRAB,Bernardo Romano,Banco República,"Av.Gral Rivera 2700, 11300 Montevideo, Departa...",Montevideo,Banco,1,Si tenés que renovar tu tarjeta anda pensando ...,es,2025-01-23 17:50:16.258000+00:00,70,False,si tenes que renovar tu tarjeta anda pensando ...,[lentitud],Negativo
4,Ci9DQUlRQUNvZENodHljRjlvT21JNFlqVklaWFIzUVUxU1...,María Eugenia García,Banco República,"Luis Battle Berres, 12800 Montevideo, Departam...",Montevideo,Banco,1,"Depositas plata, la máquina da error, no te de...",es,2025-11-13 16:45:40.276000+00:00,15,False,depositas plata la maquina da error no te devu...,"[dispensado, lentitud, disponibilidad servicio]",Negativo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,ChdDSUhNMG9nS0VJQ0FnTUNBdjlPVmpRRRAB,maicol post,Cajeros Red Brou,"4RJJ+6CW, A., Bulevar General Artigas & Av. Dr...",Montevideo,Centro comercial,1,"Te clonan la tarjeta, no usar.",es,2025-02-05 23:18:06.962000+00:00,9,False,te clonan la tarjeta no usar,[otro],Negativo
87,ChZDSUhNMG9nS0VJQ0FnTUNBMjhQYkRBEAE,Victor Lostorto,Cajeros Red Brou,"4RJJ+6CW, A., Bulevar General Artigas & Av. Dr...",Montevideo,Centro comercial,3,"La ubicación de los cajeros está excelente, lo...",es,2025-02-04 16:15:02.113000+00:00,106,False,la ubicacion de los cajeros esta excelente lo ...,[otro],Neutro
88,ChZDSUhNMG9nS0VJQ0FnTUNBemFMd093EAE,Martha Grau,Cajeros Red Brou,"4RJJ+6CW, A., Bulevar General Artigas & Av. Dr...",Montevideo,Centro comercial,5,Muy prácticos los cajeros por lo general no se...,es,2025-02-03 04:32:54.596000+00:00,132,False,muy practicos los cajeros por lo general no se...,[lentitud],Positivo
89,ChZDSUhNMG9nS0VJQ0FnSURfMl9PTUdnEAE,Perla Lapadjian,Cajeros Red Brou,"4RJJ+6CW, A., Bulevar General Artigas & Av. Dr...",Montevideo,Centro comercial,5,Es una ventaja tenerlo dentro del shopping y p...,es,2025-01-27 11:05:49.356000+00:00,150,False,es una ventaja tenerlo dentro del shopping y p...,[otro],Positivo
90,ChdDSUhNMG9nS0VJQ0FnSUNmdjR5MzhnRRAB,Nicolas Babuglia,Cajeros Red Brou,"4RJJ+6CW, A., Bulevar General Artigas & Av. Dr...",Montevideo,Centro comercial,1,"Siempre andan mal los cajeros, sinó el otro pr...",es,2025-01-03 03:14:52.310000+00:00,20,False,siempre andan mal los cajeros sino el otro pro...,[dispensado],Negativo

In [97]:
df_automatas.info()

<class 'pandas.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   reviewId                 91 non-null     str
 1   name                     91 non-null     str
 2   title                    91 non-null     str
 3   address                  91 non-null     str
 4   city                     91 non-null     str
 5   categoryName             91 non-null     str
 6   stars                    91 non-null     int64
 7   text                     91 non-null     str
 8   originalLanguage         91 non-null     str
 9   publishedAtDate          91 non-null     datetime64[us, UTC]
 10  reviewerNumberOfReviews  91 non-null     int64
 11  responseFromOwner        91 non-null     bool
 12  text_normalizado         91 non-null     str
 13  motivo_review            91 non-null     object
 14  tono                     91 non-null     str
dtypes: bool(1), datetime64[us, UTC](1), int64(2), object(1), str(10)
memory usage: 10.2+ KB

---

## 4 - Guardar

In [98]:
df_automatas.to_csv("reviews_automatas_2025.csv", index=False)
print("Archivo guardado exitosamente")

Archivo guardado exitosamente

---

Con la tabla resultante se puede saber la percepción de los clientes y cuales son los motivos principales por la cual publicaron la reseña en 2025 o, al menos, tener una primera impresión. A su vez, al ser un número manejable de registros, se podría utilizar como datos de entrenamiento para un modelo predictivo acerca del tono de nuevas reseñas al realizar una clasificación manual de las mismas.

A modo de reflexión final, si bien el objetivo principal era generar una tabla que fuera de utilidad para responder la pregunta/problema planteada (percepción de los clientes acerca del funcionamiento de los autómatas en 2025), mi idea también era aprovechar el trabajo y llegar a una tabla pronta para trabajar y poder analizar otras aristas del problema principal. Por este motivo, es que decidí dejar columnas como por ejemplo 'name' o crear la columna 'responseFromOwner'. La realidad es que no aportan al problema específico de este trabajo, pero pueden ser de utilidad para ver el problema desde otras perspectivas. Por ejemplo, varias reseñas acerca de un mismo atm y que no hubo respuesta del Banco, o un cliente que publica reseñas negativas de forma constante y que "actua" bajo un pseudónimo. Por si sola esta info aporta prácticamente nada, pero cruzandola con info interna del Banco quizá se pueda llegar a algo para aprovechar/mejorar.